#!/bin/sh

# start ssh-agent & gpg-agent
eval $(ssh-agent) &
# ssh-add ~/.ssh/id_rsa &
# ssh-add ~/.ssh/id_rsa.yeay &
eval $(gpg-agent --daemon) &

# init dbus
# if which dbus-launch >/dev/null && test -z "$DBUS_SESSION_BUS_ADDRESS"; then
  # eval $(dbus-launch --sh-syntax --exit-with-session) &
# fi

# daemonise URxvt
urxvtd -q -f -o &

# keep clipbaord in sync
autocutsel -fork &
autocutsel -selection PRIMARY -fork &
autocutsel -selection CLIPBOARD -fork &
 
# audio level +- 0dB
# amixer -- sset Headphone playback 0dB &

# compositor
# compton -CGb --no-fading-openclose &
# compton &

# system info
# conky &

# Music!
# mopidy &

# Bluetooth
# blueman-applet &

# screenlock
xautolock -time 5 -locker "i3lock -c000000" &

# desktop 
# xsetroot -solid "#404040" &
hsetroot -solid "#404040" &

# DPMS monitor setting (standby -> suspend -> off) (seconds)
# xset dpms 600 1200 2000

# mouse control
# xset m 7 10 &     # Very Fast
# xset m 5 10 &     # Faster
# xset m 3 10 &     # Normal(Fast)
# xset m default &  # System Default
# xset m 0 10 &     # Glacial

# set LCD brightness
# xbacklight -set 100 &

# set compose key
# setxkbmap -option compose:ralt &

# good work :)
exit 0
