#!/usr/bin/env zsh

CWD=$(pwd) 
DATE=$(date +"%Y%m%d%H%M")
files=(i3status.conf i3blocks.conf)

# clear old symlinks or backup old settings, if there are any
for file in $files; do
  if [ -h $HOME/.$file ] ; then
    echo "Removing stale symlink $file"
    rm $HOME/.$file
  elif [ -f $HOME/.$file ] ; then
    echo "Backing up existing ~/.$file to ~/.$file-$DATE"
    mv $HOME/.$file $HOME/.$file-$DATE
  fi
done

# create symlinks
for file in $files; do
  echo "Creating ~/.$file symlink"
  ln -s $HOME/.zsh/$file $HOME/.$file
done

printf "All done!\n"
